---
project_name: ha-fpp-mqtt

before:
  hooks:
  - go mod tidy

builds:
- id: ha-fpp-mqtt
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
  main: ./
  binary: ha-fpp-mqtt

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  name_template: "ha-fpp-mqtt-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
  format_overrides:
  - goos: windows
    format: zip
  files:
  - README.md
  - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: '{{ .Version }}-snapshot-{{ .ShortCommit }}'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs(\(.*\))?:'
    - '^test(\(.*\))?:'
    - '^ci(\(.*\))?:'
    - '^chore(\(.*\))?:'
    - '^build(\(.*\))?:'
